### PR TITLE
Return the stream response data

### PR DESCRIPTION
**Pull request by Roywcm**
I tried to save the stream activity id in my database, but figured out this data is not returned. 
Added a return to get this data.

### CODE REVIEW

**Comment by tbarbugli** [comment]
why do you want to track activity ID on your database?

**Comment by Roywcm** [comment]
To connect the dots with my models.

**Comment by Roywcm** [comment]
Wondering why this is not merged yet? I  need it to retrieve a specific activity. The only way to do this is by id, which I don' t have now.

**Comment by Roywcm** [comment]
Any updates on this? 

I have a use-case: I want my users to be able to mark activities as sticky. So in the DB I added a field "sticky" to the related model. Now I want to retrieve these sticky models but I can't add functionalities like reactions to this model, because I don't have the related ID from GetStream. How should I do this differently?

**Comment by pterk** [comment]
@Roywcm when you add an activity to stream pass it a foreign_id (your primary key is a good candidate) *and* a time as it will be guaranteed to be unique: See  https://getstream.io/docs/adding_activities/?language=java#uniqueness-foreign-ids

Next you can retrieve the activity (using the php client) with an array of arrays:

```
$response = $this->client->getActivities(null, [[$foreign_id, $timestamp]]);
```

**Comment by ferhatelmas** [comment]
Closing this since it's against callback flow and good to foreign id + time pair instead.

**Pull request closed without merging**
